config/routes.rb
RottenMangoes::Application.routes.draw do
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :destroy]
    post 'sessions/:id/alias' => 'sessions#alias', as: :sessions_alias
    post 'sessions/uncloak' => 'sessions#uncloak', as: :sessions_uncloak
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  mount_uploader :poster, PosterUploader
  
  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true}
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_past

  scope :search_title_director, lambda { |search| where('title LIKE ? OR director LIKE ?', "%#{search}%", "%#{search}%") }

  def self.in_runtime_range(time)
    case time
    when "1"
      where('runtime_in_minutes < 90') 
    when "2"
      where('runtime_in_minutes >= 90 and runtime_in_minutes < 120')
    when "3"
      where('runtime_in_minutes >= 120')
    else
      all
    end
  end

  def release_date_is_in_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

  def review_average
    (reviews.sum(:rating_out_of_ten).to_f/reviews.size).round(2) if reviews.size > 0
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true, 
                                                greater_than_or_equal_to: 1,
                                                less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :reviews, dependent: :destroy
  before_destroy :send_notification

  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create

  paginates_per 1

  def full_name
    "#{firstname} #{lastname}"
  end

  def send_notification
    UserMailer.delete_email(self).deliver
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def alias
    session[:hidden_admin] = current_user.id
    session[:user_id] = params[:id]
    redirect_to movies_path
  end

  def uncloak
    session[:user_id] = session[:hidden_admin]
    session[:hidden_admin] = nil
    redirect_to admin_users_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_access, :restrict_non_admin
  def index
    @users = Kaminari.paginate_array(User.order(:firstname)).page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "You created #{@user.firstname}"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  protected 

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def restrict_non_admin
    if !current_user.admin
      flash[:alert] = "You are not an admin!"
      redirect_to movies_path
    end
  end
      

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user, :restrict_non_admin
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.search_title_director(params[:search_term]).in_runtime_range(params[:runtime_in_minutes])
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :poster
      )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_movie, :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
  
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="admin-container">
  <h1>List of users</h1>

  <hr />

  <%= link_to "Create a new user", new_admin_user_path %>

  <hr />

  <table class="table-striped">
    <thead>
      <tr>
        <th>Username</td>
        <th>Email</td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.full_name %></td>
          <td><%= user.email %></td>
          <% unless user.admin %><td><%= button_to "Delete User", admin_user_path(user), method: :delete, class: "btn btn-default btn-delete" %></td><% else %><td></td><% end %>
          <% unless user.admin %><td><%= button_to 'Alias as user', admin_sessions_alias_path(user), class: "btn btn-default btn-alias" %></td><% else %><td></td><% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr/>

  <%= paginate @users %>
  <%= page_entries_info @users %>
</div>

app/views/admin/users/new.html.erb
<div class="admin-create-user">
  <h1>Create a new user!</h1>

  <%= form_for @user, url: admin_user_url(@user) do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, 'error') %> prevented this account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="input-group">
      <%= f.text_field :email, {class: "form-control", placeholder: "email"} %>
    </div>
    <div class="input-group">
      <%= f.text_field :firstname, {class: "form-control", placeholder: "First Name"} %>
    </div>
    <div>
    <div class="input-group">
      <%= f.text_field :lastname, {class: "form-control", placeholder: "Last Name"} %>
    </div>
    <h4>Password Fields</h4>
    <div class="input-group">
      <%= f.password_field :password, {class: "form-control", placeholder: "Enter Password..."} %>
    </div>
    <div class="input-group">
      <%= f.password_field :password_confirmation, {class: "form-control", placeholder: "Confirm Password..."} %>
    </div>
    <div class="checkbox">
      <%= f.label :admin do %>
      <%= f.check_box :admin %> Admin?
      <% end %>
    </div>
    <div>
      <div><%= f.submit "Submit", {class: "btn btn-default"} %></div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default navbar-fixed-bottom">
  <div class="footer">
    <div class="container-fluid">
      <div class="navbar-footer">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><p class="navbar-text">Signed in as <%= current_user.full_name %></p></li>
            <li>
              <span class="active">
                <p class="navbar-text"><%= link_to "Log out", session_path, {class: "navbar-link",  method: :delete }  %></p>
              </span>
            </li>
            <% if current_user.admin %>
              <li>
                <span class="active">
                  <p class="navbar-text"><%= link_to "Manage users", admin_users_path, {class: "navbar-link"} %></p>
                </span>
              </li>
            <% end %>
            <% if session[:hidden_admin] %>
              <li>
                <span class="active">
                  <p class="navbar-text"><%= link_to "Become yourself", admin_sessions_uncloak_path, {class: "navbar-link", method: :post} %></p>
                </span>
              </li>
            <% end %>
            <% else %>
              <li>
                <span class="active">
                  <p class="navbar-text"><%= link_to "Log In", new_session_path, {class: "navbar-link"} %></p>
                </span>
              </li>
              <li>
                <span class="active">
                  <p class="navbar-text"><%= link_to "Sign Up", new_user_path, {class: "navbar-link"} %></p>
                </span>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="header">
    <div class="container-fluid header">
      <div class="navbar-header">
          <ul class="nav navbar-nav">
            <li>
                <%= link_to image_tag("mango.jpg"), movies_path, class: 'navbar-logo' %>
            </li>
            <li>
              <a href="/movies">
                <h3 class="navbar-text">Rotten Mangoes</h3>
              </a>
            </li>
          </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<div class="wrapper">
  <body class="<%= controller_name %>_<%= action_name %> all-container">
    <%= render 'layouts/header' %>
    <div class="flash-container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "flash alert alert-info") %>
      <% end %>
    </div>
    <%= yield %>
    <div class="push"></div>
    <%= render 'layouts/footer' %>
  </body>
</div>
</html>

app/views/movies/_form.html.erb
<div class="movie-form">
  <%= form_for @movie, html: { multipart: true }  do |f| %>
    <% if @movie.errors.any? %>
      <div>
        <%= pluralize(@movie.errors.count, 'error') %> prevented this movie from being submitted:
        <ul>
          <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :title %><br/>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div>
      <%= f.label :release_date %><br/>
      <%= f.date_field :release_date, class: "form-control" %>
    </div>
    <div>
      <%= f.label :director %><br/>
      <%= f.text_field :director, class: "form-control" %>
    </div>
    <div>
      <%= f.label :runtime_in_minutes %><br/>
      <%= f.number_field :runtime_in_minutes, class: "form-control" %>
    </div>
    <div>
      <%= f.label :poster, "Upload Poster" %><br>
      <label class="movie-file-form btn btn-default"><%= f.file_field :poster %></label>
    </div>
    <div>
      <%= f.label :description %><br/>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="wrapper">
      <%= f.submit "Submit", {class: "btn btn-default"} %>
    </div>
  <% end %>
</div>

app/views/movies/_movie.html.erb
<div class="movie-container">
  <div class="movie-image">
    <%= link_to image_tag(movie.poster.thumb.url), movie_path(movie) %>
  </div>
  <div class="movie-details">
    <h2><%= link_to movie.title, movie_path(movie) %></h2>
    <h3><%= formatted_date(movie.release_date) %></h3>
    <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
    <% if movie.review_average %><p>Average rating: <%= movie.review_average %>/10</p><% end %>
    <p><%= movie.description %></p>
  </div>
  <div class="splitter"></div>
</div>

app/views/movies/edit.html.erb
<h2 class="movie-form">Edit movie!</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<div class="movie-index">
  <% if current_user %><%= button_to "Submit a movie!", new_movie_path, :class => "btn btn-default new-movie-btn", :method => :get %><% end %>

  <hr>

  <div class="search-form">
    <h4> Search for movies! </h4>
    <%= form_tag(movies_path, method: :get) do %>
      <div class="input-group">
        <%= text_field_tag :search_term, '', :class => "form-control" %>
      </div>
      <div class="btn-group">
        <%= radio_button_tag(:runtime_in_minutes, 1) %>
        <%= label_tag(:runtime_in_minutes, "Under 90 minutes") %>
        <%= radio_button_tag(:runtime_in_minutes, 2) %>
        <%= label_tag(:runtime_in_minutes, "Between 90 and 120 minutes") %>
        <%= radio_button_tag(:runtime_in_minutes, 3) %>
        <%= label_tag(:runtime_in_minutes, "Over 120 minutes") %>
      </div>
      <div><%= submit_tag "Search!", :class => "btn btn-default" %></div>
    <% end %>
  </div>

  <hr>
  <% @movies.each do |movie| %>
    <%= render movie %>
    <hr/>
  <% end %>
</div>

app/views/movies/new.html.erb
<h2 class="movie-form">Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= render @movie %>
<div class="movie-manage">
  <% if current_user %>
    (<%= link_to "Edit Movie", edit_movie_path(@movie) %>, <%= link_to "Delete Movie", movie_path(@movie), method: :delete, confirm: "You sure?" %>)
  <% end %>
</div> 

<hr>
<div class="review-container">
  <h3>Reviews of <em><%= @movie.title %></em></h3>
  <% if current_user %>
    <% @movie.reviews.each do |review| %>
      <p><%= review.text %></p>
      <p><%= review.rating_out_of_ten %>/10</p>
      <small>- <%= link_to review.user.full_name, user_path(review.user) %></small>
      <hr/>
    <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
  <% else %>
    <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="movie-review">
  <h2>Write a review of <em><%= @movie.title %></em>.</h2>

  <%= form_for([@movie, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div>
        <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div>
      <%= f.label :text, "Review content" %><br>
      <%= f.text_area :text, {class: "form-control"} %>
    </div>
    <div>
      <%= f.label :rating_out_of_ten %><br>
      <%= f.number_field :rating_out_of_ten, {class: "form-control"} %>
    </div>
    <div><%= f.submit "Submit", {class: "btn btn-default"} %></div>

  <% end %>
</div>

app/views/users/new.html.erb
<div class="sign-up">
  <%= image_tag("mango.jpg") %>
  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, 'error') %> prevented this account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="input-group">
      <%= f.text_field :email, {class: "form-control", placeholder: "email"} %>
    </div>
    <div class="input-group">
      <%= f.text_field :firstname, {class: "form-control", placeholder: "First Name"} %>
    </div>
    <div class="input-group">
      <%= f.text_field :lastname, {class: "form-control", placeholder: "Last Name"} %>
    </div>
    <h4>Password Fields</h4>
    <div class="input-group">
      <%= f.password_field :password, {class: "form-control", placeholder: "Enter Password..."} %>
    </div>
    <div class="input-group">
      <%= f.password_field :password_confirmation, {class: "form-control", placeholder: "Confirm Password..."} %>
    </div>
    <div>
      <div><%= f.submit "Submit", {class: "btn btn-default"} %></div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-container">
  <p><b>User:</b> <%= @user.full_name %></p>
  <p><b>Email:</b> <%= @user.email %></p>
  <h4>Reviews by this user... </h4>
  <% @user.reviews.each do |review| %>
    <p><%= review.text %> | <%= link_to Movie.find(review.movie).title, movie_path(Movie.find(review.movie)) %></p>  
  <% end %>
</div>